# Generated by Django 4.1 on 2022-08-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=30)),
                ('creditos', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('horas_cl', models.IntegerField()),
                ('horas_au', models.IntegerField()),
                ('codigo_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera')),
            ],
        ),
    ]
