# Generated by Django 4.1 on 2022-08-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo_carrera', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=30)),
                ('total_creditos', models.IntegerField()),
            ],
        ),
    ]
